### ISSUE TITLE
error: can't copy 'pendulum/formatting': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by lithammer** [python-pendulum/pendulum#334]
Installing pendulum using the new pip 19 released yesterday doesn't work anymore when using Python 2.7 on CentOS 7.

```
$ virtualenv -p /usr/bin/python2.7 env
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.
```

```
$ ./env/bin/pip install -U setuptools pip wheel
Cache entry deserialization failed, entry ignored
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl (573kB)
    100% |################################| 573kB 1.3MB/s 
Cache entry deserialization failed, entry ignored
Collecting pip
  Downloading https://files.pythonhosted.org/packages/60/64/73b729587b6b0d13e690a7c3acd2231ee561e8dd28a58ae1b0409a5a2b20/pip-19.0-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 843kB/s 
Cache entry deserialization failed, entry ignored
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip, wheel
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: wheel 0.29.0
    Uninstalling wheel-0.29.0:
      Successfully uninstalled wheel-0.29.0
Successfully installed pip-19.0 setuptools-40.6.3 wheel-0.32.3
```

```
$ ./env/bin/pip install pendulum
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pendulum
  Downloading https://files.pythonhosted.org/packages/5b/57/71fc910edcd937b72aa0ef51c8f5734fbd8c011fa1480fce881433847ec8/pendulum-2.0.4.tar.gz (75kB)
    100% |################################| 81kB 10.6MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    Complete output from command env/bin/python2.7 env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp22aSXf:
    Traceback (most recent call last):
      File "env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 67, in prepare_metadata_for_build_wheel
        config_settings)
      File "env/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 95, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-AVukBj/overlay/lib/python2.7/site-packages/poetry/masonry/api.py", line 40, in build_wheel
        poetry, SystemEnv(Path(sys.prefix)), NullIO(), Path(wheel_directory)
      File "/tmp/pip-build-env-AVukBj/overlay/lib/python2.7/site-packages/poetry/masonry/builders/wheel.py", line 49, in make_in
        wb.build()
      File "/tmp/pip-build-env-AVukBj/overlay/lib/python2.7/site-packages/poetry/masonry/builders/wheel.py", line 71, in build
        self._build(zip_file)
      File "/tmp/pip-build-env-AVukBj/overlay/lib/python2.7/site-packages/poetry/masonry/builders/wheel.py", line 92, in _build
        "python", str(setup), "build", "-b", str(self._path / "build")
      File "/tmp/pip-build-env-AVukBj/overlay/lib/python2.7/site-packages/poetry/utils/env.py", line 354, in run
        raise EnvCommandError(e)
    poetry.utils.env.EnvCommandError: Command ['env/bin/python', 'setup.py', u'build', u'-b', 'build'] errored with the following output:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/parser.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/date.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/__init__.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/period.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/duration.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/exceptions.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/datetime.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/helpers.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/__version__.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/constants.py -> build/lib.linux-x86_64-2.7/pendulum
    copying pendulum/time.py -> build/lib.linux-x86_64-2.7/pendulum
    creating build/lib.linux-x86_64-2.7/pendulum/_extensions
    copying pendulum/_extensions/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/_extensions
    copying pendulum/_extensions/helpers.py -> build/lib.linux-x86_64-2.7/pendulum/_extensions
    creating build/lib.linux-x86_64-2.7/pendulum/formatting
    copying pendulum/formatting/formatter.py -> build/lib.linux-x86_64-2.7/pendulum/formatting
    copying pendulum/formatting/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/formatting
    copying pendulum/formatting/difference_formatter.py -> build/lib.linux-x86_64-2.7/pendulum/formatting
    creating build/lib.linux-x86_64-2.7/pendulum/locales
    copying pendulum/locales/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales
    copying pendulum/locales/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales
    creating build/lib.linux-x86_64-2.7/pendulum/locales/da
    copying pendulum/locales/da/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/da
    copying pendulum/locales/da/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/da
    copying pendulum/locales/da/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/da
    creating build/lib.linux-x86_64-2.7/pendulum/locales/de
    copying pendulum/locales/de/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/de
    copying pendulum/locales/de/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/de
    copying pendulum/locales/de/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/de
    creating build/lib.linux-x86_64-2.7/pendulum/locales/en
    copying pendulum/locales/en/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/en
    copying pendulum/locales/en/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/en
    copying pendulum/locales/en/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/en
    creating build/lib.linux-x86_64-2.7/pendulum/locales/es
    copying pendulum/locales/es/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/es
    copying pendulum/locales/es/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/es
    copying pendulum/locales/es/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/es
    creating build/lib.linux-x86_64-2.7/pendulum/locales/fa
    copying pendulum/locales/fa/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fa
    copying pendulum/locales/fa/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fa
    copying pendulum/locales/fa/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fa
    creating build/lib.linux-x86_64-2.7/pendulum/locales/fo
    copying pendulum/locales/fo/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fo
    copying pendulum/locales/fo/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fo
    copying pendulum/locales/fo/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fo
    creating build/lib.linux-x86_64-2.7/pendulum/locales/fr
    copying pendulum/locales/fr/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fr
    copying pendulum/locales/fr/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fr
    copying pendulum/locales/fr/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/fr
    creating build/lib.linux-x86_64-2.7/pendulum/locales/ko
    copying pendulum/locales/ko/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/ko
    copying pendulum/locales/ko/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/ko
    copying pendulum/locales/ko/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/ko
    creating build/lib.linux-x86_64-2.7/pendulum/locales/lt
    copying pendulum/locales/lt/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/lt
    copying pendulum/locales/lt/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/lt
    copying pendulum/locales/lt/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/lt
    creating build/lib.linux-x86_64-2.7/pendulum/locales/pt_br
    copying pendulum/locales/pt_br/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/pt_br
    copying pendulum/locales/pt_br/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/pt_br
    copying pendulum/locales/pt_br/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/pt_br
    creating build/lib.linux-x86_64-2.7/pendulum/locales/zh
    copying pendulum/locales/zh/custom.py -> build/lib.linux-x86_64-2.7/pendulum/locales/zh
    copying pendulum/locales/zh/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/locales/zh
    copying pendulum/locales/zh/locale.py -> build/lib.linux-x86_64-2.7/pendulum/locales/zh
    creating build/lib.linux-x86_64-2.7/pendulum/mixins
    copying pendulum/mixins/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/mixins
    copying pendulum/mixins/default.py -> build/lib.linux-x86_64-2.7/pendulum/mixins
    creating build/lib.linux-x86_64-2.7/pendulum/parsing
    copying pendulum/parsing/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/parsing
    copying pendulum/parsing/iso8601.py -> build/lib.linux-x86_64-2.7/pendulum/parsing
    creating build/lib.linux-x86_64-2.7/pendulum/parsing/exceptions
    copying pendulum/parsing/exceptions/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/parsing/exceptions
    creating build/lib.linux-x86_64-2.7/pendulum/tz
    copying pendulum/tz/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/tz
    copying pendulum/tz/exceptions.py -> build/lib.linux-x86_64-2.7/pendulum/tz
    copying pendulum/tz/timezone.py -> build/lib.linux-x86_64-2.7/pendulum/tz
    copying pendulum/tz/local_timezone.py -> build/lib.linux-x86_64-2.7/pendulum/tz
    creating build/lib.linux-x86_64-2.7/pendulum/tz/data
    copying pendulum/tz/data/windows.py -> build/lib.linux-x86_64-2.7/pendulum/tz/data
    copying pendulum/tz/data/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/tz/data
    creating build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/transition.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/reader.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/posix_timezone.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/transition_type.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/exceptions.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    copying pendulum/tz/zoneinfo/timezone.py -> build/lib.linux-x86_64-2.7/pendulum/tz/zoneinfo
    creating build/lib.linux-x86_64-2.7/pendulum/utils
    copying pendulum/utils/__init__.py -> build/lib.linux-x86_64-2.7/pendulum/utils
    copying pendulum/utils/_compat.py -> build/lib.linux-x86_64-2.7/pendulum/utils
    error: can't copy 'pendulum/formatting': doesn't exist or not a regular file
```

**Comment by cjlint** [comment]
I am getting the exact same error except mine fails with "pendulum/_extensions" instead of "pendulum/formatting":
```error: can't copy 'pendulum/_extensions': doesn't exist or not a regular file```

I rolled back my pip to version 18.0.0 and it seems to work. I picked version 18.0.0 arbitrarily.
```pip install pip==18.0.0```

Maybe something in pip 19.0.2 exposes a bug in pendulum, or maybe pip itself has a bug

**Comment by cognifloyd** [comment]
I've tested with 19.0.1 and 19.1.1, so this issue exists at least for:

- 19.0
- 19.0.1
- 19.0.2

**Comment by cognifloyd** [comment]
Possibly related: #185
